### ISSUE TITLE
All connections to Go app fail with "Backend connection timeout" for several minutes

### ISSUE THREAD

**Issue by kevinburkeshyp** [heroku/heroku-buildpack-go#127] opened 2016-05-17 16:14 UTC
Hi,
I have a [Go app](github.com/Shyp/rickover) deployed to Heroku. It listens for incoming traffic via http.ListenAndServe on a http.Handler.

We see every request to the app fail with "Backend connection timeout" for a period of about 5 minutes. This has happened 3 times on 2 different apps in the last day. 

The app is using about 10MB of RAM, and less than 10% of the CPU (even less when it is not serving any traffic during this time).

Here's an example log line.

```
May 16 13:20:38 example heroku/router: at=error code=H19 desc="Backend connection timeout" method=PUT path="/v1/jobs/measure-connection-count/job_defb88d6-0c2c-41d7-a261-743b48a16b6c" host=example.herokuapp.com request_id=95391a09-8ded-4789-8fb6-203d4abcd23e fwd="50.16.10.49" dyno=web.1 connect=5003ms service= status=503 bytes= 
```

The app serves about 20 requests a minute, so it's not under any load. The load increases when it starts serving timeouts, since we retry after 1, 2, 4, 8, 16 seconds, but it tops out at 100 requests a minute (each served in about 10ms). I've benchmarked it with 300 concurrent requests and without any problems or similar failures, so I don't think the load is a problem.

I don't think it's the database, because if it was, we'd see the server accept requests and then either error or take a really long time to respond. We wouldn't see the server fail to accept new connections.

I don't think it's AWS, because I imagine Heroku has tools in place to detect AWS killing/rebooting machines, and migrate them. I don't think it's a network problem, since they don't normally last 5 minutes or longer. 

We don't observe similar connection timeouts on other apps written in other languages.

I'm at a loss to explain what's going on, but it's hurting our reliability. I opened a ticket, but the support engineer misdiagnosed the issue - he saw our app's retries and assumed the increased load caused the timeout, when the causation ran in the other direction. The ticket is here: https://help.heroku.com/tickets/362054

I'm opening this here in the hopes that anyone else has ran into similar problems or has ideas about how to solve it.

**Comment by freeformz** [comment] 2016-05-17 16:25
Thanks for bringing this to my attention. I'm going to close this because the issue is (likely) not related to the buildpack. I'll take a look at the app, our metrics, etc and update that ticket.

**Closed as completed by freeformz** 2016-05-17 16:25 UTC
